// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA9rfO64RK6O-7TE_eKnL2Gb4MZchKNAA',
    appId: '1:272636630794:web:eae97b15a0ede970918cf3',
    messagingSenderId: '272636630794',
    projectId: 'trial1-720cf',
    authDomain: 'trial1-720cf.firebaseapp.com',
    storageBucket: 'trial1-720cf.appspot.com',
    measurementId: 'G-5KXY6D7MED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxK7h7hJk_bwV3y61OQnoLtJ-eBnTd4Qk',
    appId: '1:272636630794:android:08446e9a27d3ad9e918cf3',
    messagingSenderId: '272636630794',
    projectId: 'trial1-720cf',
    storageBucket: 'trial1-720cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVxBwB-RdBbyhUXnf5ZxrJm9UI2h2JMy8',
    appId: '1:272636630794:ios:02c7972c45401385918cf3',
    messagingSenderId: '272636630794',
    projectId: 'trial1-720cf',
    storageBucket: 'trial1-720cf.appspot.com',
    iosClientId:
        '272636630794-t74slcnlvcgm2vb44oergi9uofqjj272.apps.googleusercontent.com',
    iosBundleId: 'com.example.learndart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVxBwB-RdBbyhUXnf5ZxrJm9UI2h2JMy8',
    appId: '1:272636630794:ios:b31f73f2d4852cc9918cf3',
    messagingSenderId: '272636630794',
    projectId: 'trial1-720cf',
    storageBucket: 'trial1-720cf.appspot.com',
    iosClientId:
        '272636630794-oevieehuv0r0ovrt0o730q79llfs0bsq.apps.googleusercontent.com',
    iosBundleId: 'com.example.learndart.RunnerTests',
  );
}
